import './globals.css'
import type { Metadata } from 'next'
import { League_Spartan } from 'next/font/google'

const spartan = League_Spartan({ 
  subsets: ['latin'],
  weight: ['500', '700']
})

export const metadata: Metadata = {
  title: 'Job Listings',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={spartan.className}>{children}</body>
    </html>
  )
}
